server.port:
  8081
#thymeleaf:
#  prefix: classpath:/templates/  #prefix??????????
#  check-template-location: true  #check-tempate-location: ??????????
#  cache: false  #cache: ?????????????false????????????????????true????????
#  suffix:  .html
#  #encoding: UTF-8
#  #content-type: text/html
#  mode: HTML5

mybatis:
  mapper-locations: classpath:mapper/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stockmanager?serverTimezone=UTC&uesUnicode=true&characterEncoding=utf8
    username: root
    password: 123

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT


#thymeleaf
thymeleaf:
  cache: false
  enabled: true
  prefix: classpath:/templates
  suffix: .html
  mode: LEGACYHTML5
  encoding: UTF-8
  servlet:
    content-type: text/html
#content-type: text/html
resources:
  chain:
    strategy:
      content:
        enabled: true
        paths: /**


mvc:
  static-path-pattern: /static/**
  favicon:
    enabled: false
  #出现错误直接报异常
  throw-exception-if-no-handler-found: true

server:
  servlet:
    context-path: ""

logging:
  level:
    com.csw.mapper: trace

